[window]
padding = { x = 4, y = 4 }
[font]
normal = { family = "monospace", style = "regular" }
size = 9
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
